coding-blocks/hacker-blocks

app/index.html, app/styles/app.scss
Signed-off-by: Arnav Gupta <arnav@codingblocks.com>
Integrates with our slack channel :)
=> add live chat widget

app/index.html, app/pods/components/ace-editor/component.js, app/pods/components/problem-view/template.hbs, app/pods/practice/index/template.hbs, app/styles/app.scss, ember-cli-build.js
=> Added chips for tags, code completion support in ace editor and snippet support

app/pods/application-error/template.hbs
@omerjerk @championswimmer @prateek27 
resolved: https://github.com/coding-blocks/hacker-blocks/issues/12
=> Improved Error Page

app/pods/loading/template.hbs, app/styles/app.scss
Issue: https://github.com/coding-blocks/hacker-blocks/issues/16
=> Updated Loader.

app/pods/components/right-side-bar/template.hbs
=> added scroll behaviour

app/pods/contests/contest/index/template.hbs
Resolved: https://github.com/coding-blocks/hacker-blocks/issues/31
=> Adding Contest Name in Contest Page

app/pods/courses/template.hbs, vendor/css/main.css
Issue #7  
Now the cards are looking:-
=> Made Course cards of same size.

app/pods/components/problem-view/template.hbs
@omerjerk 
Issue  #23
Added Title to the icons.
=> Beautify problem status icon and add title.

app/pods/online/template.hbs
pls merge n gimme boonty ponts :V
=> fix link to online course

app/pods/components/problem-view/template.hbs, app/styles/app.scss
resolved: https://github.com/coding-blocks/hacker-blocks/issues/23
=> Problem Result Icons Changed

app/styles/app.scss
resolves: https://github.com/coding-blocks/hacker-blocks/issues/61
=> Changed Card Shadow

app/pods/components/code-editor/component.js
@abhishek97 review and then deploy.
=> Altered the language order.

app/styles/app.scss
@witty123 @Prajjwal  Please review and merge.
=> changed margin

app/pods/components/code-editor/component.js, app/pods/components/code-editor/template.hbs
@Prajjwal  @witty123  Please review.
=> 15nov codeeditor login button issue

app/app.js, app/index.html, config/environment.js
Moved sentry DSN to env var. @Prajjwal @witty123  Please review.
=> moved sentry cred to env vars

app/pods/application/route.js, app/pods/components/left-side-bar/template.hbs, app/pods/components/nav-bar/template.hbs
check if model data is available then show logged in and logout button.
=> 16nov load once login

app/pods/online/template.hbs, app/styles/app.scss
@Prajjwal @witty123  Please review and merge.
=> online route ui made responsive

app/authenticators/custom.js, app/pods/components/nav-bar/component.js, app/pods/components/nav-bar/template.hbs, app/pods/logout/route.js, app/pods/logout/template.hbs, app/router.js, config/environment.js, tests/unit/pods/logout/route-test.js
Includes the following:
- Redirect to Oneauth for logout and handle callback
- Periodically refresh the JWT using `refresh_token`
=> Sso session

app/pods/users/user/template.hbs, app/styles/app.scss
@Prajjwal  @championswimmer  please review and merge.
=> Changed UI for user dashboard

config/environment.js
**What ?**
- Shifts sentry dsn to https
**Why ?**
- Sentry logging is failing
=> shift sentry dsn to https

app/pods/users/user/template.hbs, app/styles/app.scss
@Prajjwal Please review and merge.
=> alignment of batch code input label and submit fixed

app/models/user.js, app/pods/users/user/template.hbs, app/styles/app.scss
@Prajjwal @witty123 Please review and merge.
=> added codingblocks id to hackerblocks profile page

app/pods/components/current-cb-card/template.hbs, app/pods/components/nav-bar/template.hbs, app/pods/components/problem-leaderboard/template.hbs, app/styles/app.scss
The href link was removed from Hamburger 
The today's problem(DCB) now supports HTML and isn't in title property anymore. 
Leaderboard Overflow was corrected on Small Devices.
=> Updated Hamburger and DCB 

app/authenticators/custom.js, app/pods/components/nav-bar/component.js, app/pods/components/nav-bar/template.hbs, app/pods/logout/route.js, app/pods/logout/template.hbs, app/router.js, config/environment.js, tests/unit/pods/logout/route-test.js
This reverts commit 246e73c8c14b7d3e6fa8392d36edb964d8e621a5.
=> Re-apply "Sso session"

app/pods/components/problem-leaderboard/template.hbs
@Prajjwal @witty123  Please review and merge.
=> changed userid to username hashed for avatar

app/models/submission.js, app/pods/components/left-side-bar/template.hbs, app/pods/components/problem-leaderboard/template.hbs, app/pods/users/user/template.hbs
@witty123 Please review and merge.
=> fixed user photo logic

app/pods/components/current-cb-card/template.hbs
Removed double description from current cb card. Working fine on mobile.
=> Fixed DCB description

app/styles/app.scss
Fixed contest card h3 overflow, restricted to 2 lines.
=> Fixed contest card overflow

app/authenticators/custom.js, config/environment.js
=> remove refresh_token call

app/pods/users/user/controller.js, app/pods/users/user/template.hbs
Linked course name and problem name on profile page.
=> Added links on profile page

app/instance-initializers/embed.js, app/pods/application/template.hbs, tests/unit/instance-initializers/embed-test.js
@aayusharora You should use this branch as base for making the page embed-able. I've added the required initializer to introduce `embeded` flag in the controller factory. You can now use it freely inside templates, controller, and routes.
=> WIP: Make the problems page embed-able

app/models/contest.js, app/pods/components/problem-view/template.hbs, app/pods/contests/contest/index/template.hbs
=> 1. Added showTags

app/index.html, app/instance-initializers/embed.js, app/pods/dcb/index/template.hbs, app/pods/dcb/weekly-problem/index/template.hbs, app/pods/index/template.hbs
@witty123 @abhishek97  Merge this please !!
=> Iframe Layout HackerBlocks 

app/pods/components/home-statistics/template.hbs, app/pods/index/template.hbs
@witty123 Prabhu Path Pradarshit Kare.
=> Removed contest baner when Blocks of Code is not running.

app/app.js, app/pods/application/route.js
@Prajjwal  @witty123  Please review and merge.
=> 22jan sentry usercontext

app/pods/application/route.js
=> sentry usercontext

app/models/contest.js, app/pods/contests/contest/index/template.hbs, app/styles/app.scss
Here are the screenshot of the banner which I have added in the contest index page.
=> Added contestBanner.

app/models/contest.js, app/pods/contests/contest/index/template.hbs, app/styles/app.scss
=> Deploy #127

deployToProduction.sh
The timer was different on contest.problem route and contest.index route
=> Deploy: Merge pull #138

app/pods/contests/contest/route.js, app/pods/info/route.js, app/pods/info/template.hbs, app/router.js, app/styles/app.scss, app/utils/get-error-details.js, tests/unit/pods/info/route-test.js
New route handler for redirecting students to buy courses
=> Deploy #140

app/authenticators/custom.js, app/pods/application/route.js, app/utils/get-error-details.js
Dont allow users with unverified emails to proceed
=> Deploy #142

app/pods/components/problem-leaderboard/component.js, app/pods/contests/contest/index/template.hbs, app/pods/contests/contest/leaderboard/controller.js, app/pods/contests/contest/leaderboard/route.js, app/pods/contests/contest/leaderboard/template.hbs, app/router.js
Screenshot:
﻿﻿https://u.teknik.io/gEPtj.jpg
=> Add: Self refreshing, standalone contest leaderboard pages

app/pods/components/problem-leaderboard/component.js, app/pods/contests/contest/index/template.hbs, app/pods/contests/contest/leaderboard/controller.js, app/pods/contests/contest/leaderboard/route.js, app/pods/contests/contest/leaderboard/template.hbs, app/router.js
Stand alone page for leaderboard
=> Deploy #149 

app/helpers/avatarIndex.js, app/pods/components/left-side-bar/template.hbs, app/pods/components/problem-leaderboard/template.hbs, app/pods/users/user/template.hbs
@witty123  Please verify and merge.
=> removed cats and added random avatars

app/pods/components/problem-leaderboard/template.hbs
@witty123  please review and merge.
=> fixed userid for own submission

app/helpers/in.js, app/models/contest.js, app/pods/components/code-editor/template.hbs, app/pods/contests/contest/problem/template.hbs
Reverts coding-blocks/hacker-blocks#157
=> Revert "Added check to show only allowed Languages in contests."

app/pods/application/route.js
Reverts coding-blocks/hacker-blocks#173
=> Revert "auto login if we get suitable response from oneauth"

app/pods/users/user/controller.js, app/pods/users/user/template.hbs
@witty123 
Pls review. It is a fix for toast logic on adding new batch code.
=> Fix: Batch Code Logic

app/pods/contests/contest/quiz/index/route.js, app/pods/contests/contest/quiz/index/template.hbs
=> Fix: css in quiz section

app/pods/contests/contest/quiz/index/controller.js
=> Fix: quiz delete end point

app/models/competition_leaderboard.js, app/models/contest_leaderboard.js, app/models/problem_leaderboard.js, app/pods/competitions/view/route.js, app/pods/competitions/view/template.hbs, app/pods/components/college-leaderboard/component.js, app/pods/components/college-leaderboard/template.hbs, app/pods/components/problem-leaderboard/template.hbs, tests/integration/pods/components/college-leaderboard/component-test.js
Now for the leaderboard we have 2 new models
=> caching leaderboard in db
